name: Invitation to DevRhylme Foundation - GitHub Organization.
description: I would like to be part of the awesome community
title: "Please invite me to the GitHub Community Organization"
labels: [Invitation]
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Anshul Rawal
    validations:
      required: true
  - type: input
    id: discordname
    attributes:
      label: 
      placeholder: walkerheld
    validations:
      required: false
  - type: textarea
    id: Additional
    attributes:
      label: Additional Context
      description: "I learned about DevRhylme Foundation through Unstop and explored their LinkedIn page, which highlighted their focus on collaboration and growth in tech. I’m drawn to the community’s commitment to skill development and impactful projects, and I’d love to contribute while learning from like-minded individuals."
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        You can also join our [DevRhylme community](https://discord.gg/xjwZzGKDVR)
        Feel free to check out other cool repositories of the DevRhylme Foundation [here](https://github.com/DEVRhylme-Foundation)
